-- =============================================================
-- Beispieldaten für die GamesLibrary-Anwendung
-- Bilder: Steam CDN (cloudflare.steamstatic.com) bzw. Nintendo CDN
-- =============================================================

INSERT INTO games (title, description, image_url, release_date) VALUES
    ('The Legend of Zelda: Breath of the Wild',
     'Ein Open-World-Abenteuer in der Welt von Hyrule. Erkunde eine riesige Landschaft, löse Rätsel und bekämpfe Ganon.',
     'https://media.rawg.io/media/games/3ea/3ea3c9bbd940b6cb7f2139e42d3d443f.jpg',
     '2017-03-03'),
    ('The Witcher 3: Wild Hunt',
     'Ein epiges Rollenspiel in einer offenen Fantasiewelt. Spiele als Hexer Geralt und jage Monster.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/292030/header.jpg',
     '2015-05-19'),
    ('Red Dead Redemption 2',
     'Ein Western-Epos über Ehre und Überleben im untergehenden Wilden Westen. Mit eindrucksvoller Open World.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/1174180/header.jpg',
     '2018-10-26'),
    ('Cyberpunk 2077',
     'Ein Action-RPG in der dystopischen Megacity Night City. Du spielst als V und kämpfst um Unsterblichkeit.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/1091500/header.jpg',
     '2020-12-10'),
    ('God of War (2018)',
     'Kratos reist mit seinem Sohn Atreus durch die nordische Mythologie. Packende Story und beeindruckende Kämpfe.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/1593500/header.jpg',
     '2018-04-20'),
    ('Minecraft',
     'Ein Sandbox-Spiel ohne Grenzen. Baue, erkunde und überlebe in einer prozedural generierten Blockwelt.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/1672970/header.jpg',
     '2011-11-18'),
    ('Among Us',
     'Ein Social-Deduction-Spiel, bei dem Crewmitglieder gemeinsam Aufgaben erfüllen und Verräter entlarven müssen.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/945360/header.jpg',
     '2018-06-15'),
    ('Elden Ring',
     'Ein herausforderndes Action-RPG von FromSoftware in einer von George R.R. Martin mitgestalteten Welt.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/1245620/header.jpg',
     '2022-02-25'),
    ('Hollow Knight',
     'Ein atmosphärisches Metroidvania in einem unterirdischen Insektenreich. Präzise Kämpfe und tiefe Erkundung.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/367520/header.jpg',
     '2017-02-24'),
    ('Stardew Valley',
     'Ein Farming-Simulator mit RPG-Elementen. Baue eine Farm auf, pflege Freundschaften und entdecke Geheimnisse.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/413150/header.jpg',
     '2016-02-26'),
    ('Portal 2',
     'Ein brillantes Rätselspiel mit Portalmechanik. Alleine oder im Koop mit einem Freund durch knifflige Testkammern.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/620/header.jpg',
     '2011-04-19'),
    ('Baldur''s Gate 3',
     'Ein episches Rollenspiel basierend auf Dungeons & Dragons. Triff Entscheidungen, die die Welt verändern.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/1086940/header.jpg',
     '2023-08-03'),
    ('Hades',
     'Ein roguelike Action-Spiel, in dem du als Sohn des Hades aus der Unterwelt ausbrichst. Mit exzellenter Story.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/1145360/header.jpg',
     '2020-09-17'),
    ('Hades II',
     'Der Nachfolger des preisgekrönten Hades. Spiele als Melinoe und kämpfe dich durch die Unterwelt.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/1145350/header.jpg',
     '2024-05-06'),
    ('Celeste',
     'Ein herausforderndes Plattformspiel über eine junge Frau, die einen mysteriösen Berg besteigt.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/504230/header.jpg',
     '2018-01-25'),
    ('Dead Cells',
     'Ein roguelike Metroidvania mit blitzschnellen Kämpfen und einer sich ständig verändernden Welt.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/588650/header.jpg',
     '2018-08-07'),
    ('Terraria',
     'Ein 2D-Sandbox-Abenteuer voller Erkundung, Bauen und Kämpfen gegen hunderte von Monstern und Bossen.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/105600/header.jpg',
     '2011-05-16'),
    ('Cuphead',
     'Ein extrem schwieriger Run-and-Gun-Shooter im Stil der 1930er-Zeichentrickfilme. Wunderschöne Handzeichnungen.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/268910/header.jpg',
     '2017-09-29'),
    ('Dark Souls III',
     'Das dritte Kapitel der legendären Dark-Souls-Reihe. Kämpfe gegen furchteinflössende Bosse in einer sterbenden Welt.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/374320/header.jpg',
     '2016-04-12'),
    ('Dark Souls Remastered',
     'Die überarbeitete Version des Klassikers, der das Souls-Genre definiert hat. Anspruchsvoll und unvergesslich.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/570940/header.jpg',
     '2018-05-25'),
    ('Sekiro: Shadows Die Twice',
     'Ein Samurai-Action-Spiel von FromSoftware im feudalen Japan. Präzise Schwertkämpfe und ein Hauch Magie.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/814380/header.jpg',
     '2019-03-22'),
    ('Monster Hunter: World',
     'Jage riesige Monster in atemberaubenden Ökosystemen. Sammle Ressourcen und schmiedebeeindruckende Ausrüstung.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/582010/header.jpg',
     '2018-08-09'),
    ('Monster Hunter Rise',
     'Der nächste Teil der Monster-Hunter-Reihe mit neuen Bewegungsmöglichkeiten und dem Wirebug-System.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/1446780/header.jpg',
     '2022-01-12'),
    ('Resident Evil Village',
     'Ein Survival-Horror-Spiel aus der Egoperspektive. Ethan Winters kämpft in einem mysteriösen Dorf um sein Leben.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/1196590/header.jpg',
     '2021-05-07'),
    ('Resident Evil 2',
     'Das Remake des Klassikers. Leon und Claire kämpfen ums Überleben in einem von Zombies befallenen Raccoon City.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/883710/header.jpg',
     '2019-01-25'),
    ('Devil May Cry 5',
     'Rasante Hack-and-Slash-Action mit drei spielbaren Charakteren und atemberaubenden Combos gegen Dämonen.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/601150/header.jpg',
     '2019-03-08'),
    ('NieR: Automata',
     'Ein Action-RPG über Androiden und Maschinenwesen in einer postapokalyptischen Welt. Tiefgründige Story.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/524220/header.jpg',
     '2017-03-07'),
    ('Persona 5 Royal',
     'Ein stylisches JRPG, in dem Gymnasiasten tagsüber ein normales Leben führen und nachts als Phantomdiebe agieren.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/1687950/header.jpg',
     '2022-10-21'),
    ('Final Fantasy VII Remake',
     'Die moderne Neuinterpretation des JRPG-Klassikers. Cloud und seine Verbündeten kämpfen gegen den Shinra-Konzern.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/1462040/header.jpg',
     '2021-12-16'),
    ('Disco Elysium',
     'Ein einzigartiges RPG ohne Kämpfe. Du spielst einen kaputten Detektiv, der einen Mordfall löst und sich selbst findet.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/632470/header.jpg',
     '2019-10-15'),
    ('Divinity: Original Sin 2',
     'Ein rundenbasiertes Rollenspiel mit tiefem Kampfsystem, vollständigem Koop und einer packenden Geschichte.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/435150/header.jpg',
     '2017-09-14'),
    ('It Takes Two',
     'Ein kooperatives Abenteuer für zwei Spieler. Ein zerstrittenes Ehepaar muss zusammenarbeiten, um wieder zueinanderzufinden.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/1426210/header.jpg',
     '2021-03-26'),
    ('A Plague Tale: Innocence',
     'Ein emotionales Abenteuer im Frankreich des 14. Jahrhunderts. Amicia beschützt ihren kleinen Bruder vor Pest und Inquisition.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/752590/header.jpg',
     '2019-05-14'),
    ('A Plague Tale: Requiem',
     'Der Nachfolger von Innocence. Amicia und Hugo setzen ihre Flucht fort und suchen eine Heilung für den Fluch.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/1741390/header.jpg',
     '2022-10-18'),
    ('Horizon Zero Dawn',
     'In einer Welt, die von Maschinen bevölkert wird, kämpft die Jägerin Aloy um die Wahrheit über ihre Herkunft.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/1151640/header.jpg',
     '2020-08-07'),
    ('Death Stranding',
     'Ein einzigartiges Action-Spiel von Hideo Kojima. Verbinde eine zersplitterte Gesellschaft in einem postapokalyptischen Amerika.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/1190460/header.jpg',
     '2020-07-14'),
    ('Ori and the Will of the Wisps',
     'Ein wunderschönes Metroidvania mit malerischen Grafiken, herzerwärmender Geschichte und präzisen Plattformpassagen.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/1057090/header.jpg',
     '2020-03-11'),
    ('Ori and the Blind Forest',
     'Der Vorgänger von Will of the Wisps. Ori kämpft darum, den sterbenden Wald zu retten. Emotional und atemberaubend.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/261570/header.jpg',
     '2015-03-11'),
    ('Valheim',
     'Ein Viking-Survival-Spiel in einer prozedural generierten Welt. Baue, erkunde und besiege mythologische Bosse.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/892970/header.jpg',
     '2021-02-02'),
    ('No Man''s Sky',
     'Erkunde ein unendliches, prozedural generiertes Universum mit Milliarden von Planeten. Heute eines der besten Comebacks der Gaming-Geschichte.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/275850/header.jpg',
     '2016-08-12'),
    ('Subnautica',
     'Überlebe auf einem fremden Ozeanplaneten. Erkunde die Tiefen des Meeres und entdecke außerirdisches Leben.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/264710/header.jpg',
     '2018-01-23'),
    ('Sons of the Forest',
     'Der Nachfolger von The Forest. Überlebe in einem dichten Wald voller Kannibalen und suche nach dem Vermissten.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/1326470/header.jpg',
     '2023-02-23'),
    ('Phasmophobia',
     'Ein kooperatives Horror-Spiel, in dem du als Geisterjäger übernatürliche Erscheinungen in verlassenen Gebäuden untersuchst.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/739630/header.jpg',
     '2020-09-18'),
    ('Fall Guys',
     'Ein chaotisches Battle-Royale-Party-Spiel mit bunten Mini-Games. 60 Spieler kämpfen um die goldene Krone.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/1097150/header.jpg',
     '2020-08-04'),
    ('PUBG: Battlegrounds',
     'Der Pionier des Battle-Royale-Genres. 100 Spieler springen auf eine Insel, nur einer überlebt.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/578080/header.jpg',
     '2017-12-20'),
    ('Rainbow Six Siege',
     'Ein taktischer Mehrspieler-Shooter mit zerstörbaren Umgebungen und über 60 spielbaren Operatoren.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/359550/header.jpg',
     '2015-12-01'),
    ('Sea of Thieves',
     'Ein kooperatives Piraten-Abenteuer. Segele mit deiner Crew, plündere Schätze und kämpfe gegen andere Piraten.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/1172620/header.jpg',
     '2018-03-20'),
    ('Forza Horizon 5',
     'Das bisher grösste und vielfältigste Forza Horizon. Renne durch Mexico in atemberaubenden Fahrzeugen.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/1551360/header.jpg',
     '2021-11-09'),
    ('Rust',
     'Ein hartes Survival-Spiel. Starte nackt, baue eine Basis, schmiedeWaffen und überlebe gegen andere Spieler.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/252490/header.jpg',
     '2018-02-08'),
    ('The Last of Us Part I',
     'Erlebe die emotionale Reise von Joel und Ellie durch eine postapokalyptische USA in dieser kompletten Neuauflage.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/1888930/header.jpg',
     '2023-03-28'),
    ('Ghost of Tsushima',
     'Ein Samurai-Open-World-Spiel im feudalen Japan. Kämpfe als Jin Sakai gegen die mongolische Invasion.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/2215430/header.jpg',
     '2024-05-16'),
    ('Marvel''s Spider-Man Remastered',
     'Schwingt als Peter Parker durch New York, stoppt Verbrechen und stellt sich mächtigen Schurken. Atemberaubende Grafik.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/1817070/header.jpg',
     '2022-08-12'),
    ('Returnal',
     'Ein roguelike Third-Person-Shooter auf einem feindseligen Alien-Planeten. Jeder Tod bringt dich zum Anfang zurück.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/1649240/header.jpg',
     '2023-02-15'),
    ('Ratchet & Clank: Rift Apart',
     'Ein interdimensionales Abenteuer mit dem dynamischen Duo. Springt durch Dimensionsrisse und rettet das Universum.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/1895880/header.jpg',
     '2023-07-26'),
    ('Don''t Starve Together',
     'Ein Koop-Survival-Spiel in einer düsteren, gotischen Welt. Sammle Ressourcen, koche Essen und überlebe den Winter.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/322330/header.jpg',
     '2016-04-21'),
    ('Half-Life: Alyx',
     'Das bahnbrechende VR-Meisterwerk von Valve. Alyx Vance kämpft im Vorfeld der Ereignisse von Half-Life 2.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/546560/header.jpg',
     '2020-03-23'),
    ('Crisis Core: Final Fantasy VII Reunion',
     'Das Prequel zu Final Fantasy VII. Erlebe Zacks Geschichte als SOLDIER in Midgar und auf dem Schlachtfeld.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/1887860/header.jpg',
     '2022-12-13'),
    ('ARK: Survival Evolved',
     'Überlebe auf einer Insel voller Dinosaurier. Zähme urzeitliche Kreaturen, baue Stützpunkte und entwickle dich weiter.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/346110/header.jpg',
     '2017-08-29');

-- Batch 2: Weitere verifizierte Spiele (alle URLs HTTP 200 getestet)
INSERT INTO games (title, description, image_url, release_date) VALUES
    ('Counter-Strike 2',
     'Der kompetitivste Taktik-Shooter der Welt. Teams aus Terroristen und Gegenterroristen kämpfen in rasanten Runden.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/730/header.jpg',
     '2023-09-27'),
    ('Grand Theft Auto V',
     'Drei Kriminelle in Los Santos: Michael, Trevor und Franklin kämpfen in einem Heist-Epos um Ruhm, Geld und Freiheit.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/271590/header.jpg',
     '2015-04-14'),
    ('Half-Life 2',
     'Gordon Freeman kehrt zurück. Ein Meilenstein der Spielgeschichte mit packender Physik-Engine und fesselnder Story.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/220/header.jpg',
     '2004-11-16'),
    ('Left 4 Dead 2',
     'Kooperativer Zombie-Survival-Shooter für vier Spieler. Kämpfe durch apokalyptische Szenarien mit vielfältigen Waffen.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/550/header.jpg',
     '2009-11-17'),
    ('DOOM (2016)',
     'Der Reboot des legendären Shooters. Brutale, schnelle Action gegen Dämonen auf dem Mars und in der Hölle.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/379720/header.jpg',
     '2016-05-13'),
    ('DOOM Eternal',
     'Der Doom Slayer kehrt zurück. Noch schneller, noch brutaler – mit einem herausfordernden Ressourcenmanagement.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/782330/header.jpg',
     '2020-03-20'),
    ('Slay the Spire',
     'Ein Deck-Building-Roguelike. Baue ein einzigartiges Kartendeck und kämpfe dich durch einen mysteriösen Turm.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/646570/header.jpg',
     '2019-01-23'),
    ('Deep Rock Galactic',
     'Kooperativer Shooter für 1–4 Spieler. Tauche als Space-Zwerg in gefährliche Höhlen und ernte seltene Ressourcen.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/548430/header.jpg',
     '2020-05-13'),
    ('Risk of Rain 2',
     'Ein roguelike Third-Person-Shooter. Je länger du überlebst, desto stärker – und gefährlicher – wird das Spiel.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/632360/header.jpg',
     '2020-08-11'),
    ('Outer Wilds',
     'Ein Erkundungsspiel in einem Sonnensystem in einer 22-Minuten-Zeitschleife. Eines der tiefgründigsten Spiele überhaupt.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/753640/header.jpg',
     '2020-06-18'),
    ('Return of the Obra Dinn',
     'Ein rätselhaftes Detektivspiel: Untersuche ein Geisterschiff und finde heraus, was mit der Crew passiert ist.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/653530/header.jpg',
     '2018-10-18'),
    ('Firewatch',
     'Ein atmosphärisches Abenteuer im Yellowstone-Wald. Als Feuerwächter Henry entdeckst du ein dunkles Geheimnis.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/383870/header.jpg',
     '2016-02-09'),
    ('Vampire Survivors',
     'Ein hypnotisches Roguelike: Überlebe endlose Horden von Monstern mit automatischen Angriffen und mächtigen Power-ups.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/1794680/header.jpg',
     '2022-10-20'),
    ('Stray',
     'Spiele als streunende Katze in einer neon-beleuchteten Cyberpunk-Stadt. Erkunde, schnappe und löse Rätsel.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/1332010/header.jpg',
     '2022-07-19'),
    ('Assassin''s Creed Odyssey',
     'Erkunde das antike Griechenland als Alexios oder Kassandra. Riesige Open World, Seeschlachten und mythologische Kreaturen.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/812140/header.jpg',
     '2018-10-05'),
    ('Dishonored 2',
     'Ein Stealth-Action-Spiel in einer viktorianischen Dampfpunk-Welt. Spiele als Corvo oder Emily mit einzigartigen Kräften.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/403640/header.jpg',
     '2016-11-11'),
    ('Kingdom Come: Deliverance',
     'Ein realistisches mittelalterliches RPG ohne Magie oder Drachen. Kämpfe, verhandle und überlebe im Böhmen des 15. Jahrhunderts.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/379430/header.jpg',
     '2018-02-13'),
    ('Dying Light 2: Stay Human',
     'Ein parkourbasiertes Open-World-Zombie-Spiel. Tagsüber Erkundung, nachts Überleben gegen hungrige Infizierte.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/534380/header.jpg',
     '2022-02-04'),
    ('Frostpunk 2',
     'Führe eine Gesellschaft durch eine globale Eiszeit. Triff schwere moralische Entscheidungen zwischen Überleben und Menschlichkeit.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/1620230/header.jpg',
     '2024-09-20'),
    ('Final Fantasy XV',
     'Noctus und seine drei Freunde reisen durch eine offene Welt auf der Suche nach dem Kristall. Action-RPG mit emotionaler Story.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/637650/header.jpg',
     '2018-03-06'),
    ('Final Fantasy XVI',
     'Ein dunkles Action-RPG im Mittelalter-Fantasy-Setting. Clive Rosfield kämpft um Freiheit und Rache in einer brutalen Welt.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/2515020/header.jpg',
     '2024-09-17'),
    ('Lies of P',
     'Ein düsteres Souls-like in einer steampunkigen Welt. Spiele als Pinocchio und kämpfe gegen mechanische Monstern.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/1627720/header.jpg',
     '2023-09-19'),
    ('Star Wars Jedi: Fallen Order',
     'Spiele als Cal Kestis, ein junger Jedi auf der Flucht vor dem Imperium. Souls-inspirierter Kampf mit Lichtschwert und Macht.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/1172380/header.jpg',
     '2019-11-15'),
    ('Grounded',
     'Du bist auf Insektengrösse geschrumpft und kämpfst im Hintergarten ums Überleben. Koop-Survival mit Riesenkäfern.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/962130/header.jpg',
     '2022-09-27'),
    ('Deathloop',
     'Du steckst in einer Zeitschleife auf einer Insel fest. Eliminiere acht Ziele in einem Tag – bevor sie dich eliminieren.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/1252330/header.jpg',
     '2021-09-14'),
    ('Satisfactory',
     'Baue riesige Fabriken auf einem fremden Planeten. Automatisiere die gesamte Ressourcengewinnung in einer 3D-Open-World.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/526870/header.jpg',
     '2020-06-08'),
    ('Factorio',
     'Baue und verwalte automatisierte Fabriken auf einem fremden Planeten. Das süchtig machendste Management-Spiel aller Zeiten.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/427520/header.jpg',
     '2020-08-14'),
    ('RimWorld',
     'Ein Koloniesimulations-RPG, das zufällige Geschichten erzählt. Baue eine Kolonie, manage Charaktere und überlebe das Chaos.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/294100/header.jpg',
     '2018-10-17'),
    ('Ghostrunner',
     'Ein blitzschneller Cyberpunk-Slasher in der Egoperspektive. Ein Treffer, tot. Fliesse durch neon-beleuchtete Levels.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/1235960/header.jpg',
     '2020-10-27'),
    ('Ghostrunner 2',
     'Der Nachfolger des Cyberpunk-Slashers. Noch mehr Speed, neue Kräfte und atemberaubende Motorrad-Sequenzen.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/1835370/header.jpg',
     '2023-10-26'),
    ('Little Nightmares II',
     'Ein atmosphärischer Horror-Plattformer. Mono und Six fliehen durch eine alptraumhafte Welt voller grotesker Kreaturen.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/860510/header.jpg',
     '2021-02-11'),
    ('Tunic',
     'Ein charmantes Action-Adventure als kleiner Fuchs in einer geheimnisvollen Welt. Rätsel, Bosse und ein verstecktes Alphabet.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/553420/header.jpg',
     '2022-03-16'),
    ('SUPERHOT',
     'Zeit bewegt sich nur, wenn du dich bewegst. Ein einzigartiger Ego-Shooter, der Puzzle und Action vereint.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/322500/header.jpg',
     '2016-02-25'),
    ('Enter the Gungeon',
     'Ein Bullet-Hell-Roguelike mit Waffenhumor. Kämpfe dich durch ein Verlies voller lebendiger Kugeln auf der Suche nach der Vergangenheit.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/311690/header.jpg',
     '2016-04-05'),
    ('Apex Legends',
     'Ein Battle-Royale-Shooter mit einzigartigen Legenden und ihren Fähigkeiten. Schnelles, teambasiertes Gameplay auf grossen Karten.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/1172470/header.jpg',
     '2020-11-04'),
    ('Nioh 2: Complete Edition',
     'Ein Souls-ähnliches Action-RPG im feudalen Japan. Kämpfe gegen Yokai-Dämonen mit einem tiefen Waffensystem.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/1325200/header.jpg',
     '2021-02-05'),
    ('Street Fighter 6',
     'Das neueste Kapitel der legendären Kampfspiel-Reihe. Moderne Steuerung, epische Story und ein riesiger Roster.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/1627280/header.jpg',
     '2023-06-02'),
    ('Mortal Kombat 1',
     'Ein neues Kapitel im MK-Universum nach Liu Kangs Zeitreset. Brutale Fatalities, Kameo-Fighter und tiefe Story.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/1971870/header.jpg',
     '2023-09-19'),
    ('Tekken 8',
     'Das neueste Tekken mit cineastischen Kämpfen und einem revolutionären Heat-System. Mishima-Saga erreicht ihren Höhepunkt.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/1778820/header.jpg',
     '2024-01-26'),
    ('Dragon Ball FighterZ',
     'Ein 2D-Kampfspiel mit atemberaubenden Animationseffekten im Dragon-Ball-Stil. 3-gegen-3-Kämpfe auf höchstem Niveau.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/678950/header.jpg',
     '2018-01-26'),
    ('Alan Wake Remastered',
     'Ein psychologischer Horror-Thriller. Autor Alan Wake kämpft in einer düsteren Kleinstadt gegen die Dunkelheit mit Licht als Waffe.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/1814760/header.jpg',
     '2021-10-05');

-- Batch 3: Rollenspiele & Open-World-Klassiker
INSERT INTO games (title, description, image_url, release_date) VALUES
    ('The Elder Scrolls V: Skyrim Special Edition',
     'Der Dragonborn erwacht. Erkunde die verschneiten Gipfel und tiefen Dungeons Skyrims, töte Drachen und entschlüssele Rufe.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/489830/header.jpg',
     '2016-10-28'),
    ('Mass Effect Legendary Edition',
     'Die epische Sci-Fi-Trilogie in einem Bundle. Steuere Commander Shepard durch drei Spiele und rette die Galaxis vor den Reapern.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/1328670/header.jpg',
     '2021-05-14'),
    ('Fallout 4',
     'Ein postapokalyptisches RPG in den Trümmern Bostons. Baue Siedlungen, kämpfe gegen Mutanten und suche nach deinem verlorenen Sohn.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/377160/header.jpg',
     '2015-11-10'),
    ('BioShock Remastered',
     'Tauche ein in Rapture – eine versunkene Art-Déco-Unterwasserstadt. Ein Meisterwerk des Immersive-Sim-Genres mit packender Atmosphäre.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/409710/header.jpg',
     '2016-09-15'),
    ('Prey (2017)',
     'Du erwachst auf der Raumstation Talos I, die von Aliens befallen ist. Ein tiefgründiges Immersive-Sim mit unzähligen Lösungswegen.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/480490/header.jpg',
     '2017-05-05'),
    ('Hitman World of Assassination',
     'Agent 47 auf seiner tödlichsten Mission. Meisterhaftes Stealth-Gameplay in weitläufigen, lebendigen Levels rund um den Globus.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/1659040/header.jpg',
     '2023-01-20'),
    ('Titanfall 2',
     'Eines der besten Shooter-Singleplayer-Kampagnen aller Zeiten. Pilot und Titan kämpfen Seite an Seite in rasanten Sci-Fi-Schlachten.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/1237970/header.jpg',
     '2016-10-28'),
    ('Control',
     'Du übernimmst das Federal Bureau of Control in einem brutalistischen Gebäude voller paranormaler Kräfte. Surreal und faszinierend.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/870780/header.jpg',
     '2020-08-27'),
    ('Pathfinder: Wrath of the Righteous',
     'Ein riesiges cRPG-Epos. Werde zum Crusader Commander und führe Armeen in einem dämonischen Kreuzzug. Tiefes D&D-Regelwerk.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/1184370/header.jpg',
     '2021-09-02'),
    ('The Witcher 2: Assassins of Kings',
     'Das Prequel zu Wild Hunt. Geralt steckt mitten in politischen Intrigen und muss einen Königsmörder aufspüren. Packende Entscheidungen.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/20920/header.jpg',
     '2011-05-17'),
    ('Dragon Age: Origins',
     'Das dunkle Fantasy-RPG von BioWare. Wähle deinen Ursprung, führe eine Armee gegen die Dunkle Brut und opfere alles für Ferelden.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/47810/header.jpg',
     '2009-11-03'),
    ('Fallout: New Vegas',
     'Im Ödland des Mojave kämpft ein Kurier um Rache und Macht. Das beliebteste Fallout mit unzähligen Fraktionen und Endungen.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/22380/header.jpg',
     '2010-10-19'),
    ('Pillars of Eternity II: Deadfire',
     'Ein klassisches cRPG auf hoher See. Jage einen entflohenen Gott durch einen Inselarchipel und bestimme das Schicksal der Welt.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/560130/header.jpg',
     '2018-05-08'),
    ('Wasteland 3',
     'Taktisches post-apokalyptisches RPG in Colorado. Führe die Desert Rangers, schmiedet Allianzen und triff moralisch schwere Entscheidungen.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/719040/header.jpg',
     '2020-08-28'),
    ('Star Wars: Knights of the Old Republic II',
     'Eines der tiefgründigsten Star-Wars-Spiele je gemacht. Erkunde die dunkle Seite der Macht 5 Jahre nach dem ersten KOTOR.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/208580/header.jpg',
     '2013-07-18'),
    ('Planescape: Torment: Enhanced Edition',
     'Das philosophischste RPG überhaupt. Was kann das Wesen eines Mannes verändern? Erkunde die Ebenen der Existenz als Unsterblicher.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/466300/header.jpg',
     '2017-04-11'),
    ('XCOM 2',
     'Taktisches Rundenstrategiespiel. Die Aliens haben die Erde besetzt – führe den Widerstand XCOM aus dem Untergrund gegen die Unterdrücker.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/268500/header.jpg',
     '2016-02-05'),
    ('Divinity: Original Sin (Enhanced Edition)',
     'Der Vorgänger des grandiosen DOS2. Zwei Source Hunters lösen Mordfälle in einer bunten Fantasiewelt mit vollständigem Koop-Modus.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/373420/header.jpg',
     '2015-10-27'),
    ('FTL: Faster Than Light',
     'Steuere ein Raumschiff durch feindliche Galaxien. Jedes Run ist einzigartig – verwalte Crew, Systeme und kämpfe gegen feindliche Schiffe.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/212680/header.jpg',
     '2012-09-14'),
    ('Into the Breach',
     'Rundenbasiertes Taktikspiel gegen riesige Käfer. Kontrolliere Mechs und rette die Welt – jede Entscheidung ist sichtbar und berechenbar.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/590380/header.jpg',
     '2018-02-27'),
    ('Torchlight II',
     'Ein schnelles Action-RPG im bunten Stil von Diablo. Erkunde prozedural generierte Dungeons mit einem treuen Haustier-Begleiter.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/200710/header.jpg',
     '2012-09-20'),
    ('Path of Exile',
     'Das komplexeste Action-RPG der Welt. Baue einzigartige Charaktere mit einem riesigen Skill-Tree und kämpfe dich durch düstere Welten.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/238960/header.jpg',
     '2013-10-23'),
    ('Wolfenstein II: The New Colossus',
     'BJ Blazkowicz kämpft um die Befreiung Amerikas von der Nazi-Besatzung. Brutal, schnell und mit einer überraschend emotionalen Story.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/612880/header.jpg',
     '2017-10-27'),
    ('The Outer Worlds',
     'Ein Retro-Sci-Fi-RPG von Obsidian. Erkunde Kolonien am Rande des Universums und entscheide, ob du Korporationen oder Rebellen hilfst.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/1007830/header.jpg',
     '2020-10-23'),
    ('Metro Exodus',
     'Artyom verlässt die Moskauer Metro und erkundet ein post-apokalyptisches Russland. Atemberaubende Grafik, packende Story, hartes Überleben.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/412020/header.jpg',
     '2020-02-14');

-- Batch 4: Survival, Strategie & Indie-Meisterwerke
INSERT INTO games (title, description, image_url, release_date) VALUES
    ('The Long Dark',
     'Überlebe in einer einsamen kanadischen Wildnis nach einem geomagnetischen Sturm. Kein Zombie, nur die Natur gegen dich. Tiefe Immersion.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/305620/header.jpg',
     '2017-08-01'),
    ('Frostpunk',
     'Die letzte Stadt der Erde kämpft gegen den ewigen Winter. Führe deine Gesellschaft, triff unmögliche Entscheidungen – Überleben hat seinen Preis.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/323190/header.jpg',
     '2018-04-24'),
    ('Oxygen Not Included',
     'Baue eine Kolonie im Asteroideninneren. Manage Sauerstoff, Wärme, Nahrung und die psychische Gesundheit deiner Dupes. Unendlich komplex.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/457140/header.jpg',
     '2019-07-30'),
    ('Dwarf Fortress',
     'Das tiefste Aufbau-Spiel überhaupt. Baue eine Festung mit Zwergen, manage deren Leben und Launen – bis die Festung unvermeidlich untergeht.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/975370/header.jpg',
     '2022-12-06'),
    ('Crusader Kings III',
     'Herrsche als mittelalterlicher Monarch über Generationen. Heirate strategisch, intrigiere gegen Rivalen und forme eine Dynastie für die Ewigkeit.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/1158310/header.jpg',
     '2020-09-01'),
    ('Europa Universalis IV',
     'Regiere eine Nation von 1444 bis 1821. Das tiefste Geschichtsstrategie-Spiel der Welt mit tausenden Stunden an Kampagnen und Mods.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/236850/header.jpg',
     '2013-08-13'),
    ('Stellaris',
     'Aufbau-Strategie im Weltall. Gründe ein galaktisches Imperium, erforsche fremde Zivilisationen und kämpfe in epischen Raumschlachten.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/281990/header.jpg',
     '2016-05-09'),
    ('Hearts of Iron IV',
     'Führe eine Nation durch den Zweiten Weltkrieg. Das tiefste Kriegsstrategie-Spiel: Plane Angriffe, manage Ressourcen und forme die Geschichte.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/394360/header.jpg',
     '2016-06-06'),
    ('Total War: WARHAMMER III',
     'Riesige Fantasy-Schlachten in der Warhammer-Welt. Steuere Armeen aus Chaos-Kriegern, Ogern, Cathayern und mehr in epischen Kampagnen.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/1142710/header.jpg',
     '2022-02-17'),
    ('Age of Empires IV',
     'Die Rückkehr des Echtzeit-Strategie-Klassikers. Führe historische Zivilisationen durch das Mittelalter und besiege deine Feinde durch Taktik.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/1466860/header.jpg',
     '2021-10-28'),
    ('Victoria 3',
     'Führe eine Nation durch das 19. Jahrhundert. Industrialisierung, Diplomatie, soziale Reformen – forme die Moderne nach deinem Willen.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/529340/header.jpg',
     '2022-10-25'),
    ('Dota 2',
     'Das tiefste Multiplayer-Online-Battle-Arena-Spiel der Welt. Wähle aus über 120 Helden und kämpfe in strategischen 5-gegen-5-Schlachten.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/570/header.jpg',
     '2013-07-09'),
    ('Team Fortress 2',
     'Der legendäre Klassen-Shooter von Valve. Neun einzigartige Charaktere kämpfen in chaotischen, humorvollen Team-Schlachten gegeneinander.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/440/header.jpg',
     '2007-10-10'),
    ('Rocket League',
     'Fussball mit Raketen-betriebenen Autos. Einfach zu lernen, fast unmöglich zu meistern – mit einer der leidenschaftlichsten Gaming-Communitys.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/252950/header.jpg',
     '2015-07-07'),
    ('Warframe',
     'Ein kostenloser Third-Person-Shooter mit Ninjas im Weltraum. Massiver Content, einzigartiges Bewegungssystem und eine tiefe Lore.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/230410/header.jpg',
     '2013-03-25'),
    ('Destiny 2',
     'Ein Looter-Shooter in einer postapokalyptischen Science-Fantasy-Welt. Kämpfe als Hüter und schütze die letzte Stadt der Menschheit.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/1085660/header.jpg',
     '2019-10-01'),
    ('Borderlands 2',
     'Ein Looter-Shooter mit unverwechselbarem Comic-Stil. Jagd nach Millionen von prozedural generierten Waffen auf dem Planeten Pandora.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/49520/header.jpg',
     '2012-09-18'),
    ('Borderlands 3',
     'Der modernisierte Nachfolger: vier neue Kammerjäger, verbessertes Gunplay und eine riesige Waffenauswahl über mehrere Planeten.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/397540/header.jpg',
     '2020-03-13'),
    ('Far Cry 5',
     'Befreie Hope County, Montana, von einem apokalyptischen Kult. Open-World-Shooter mit Koop, fliegbaren Flugzeugen und tierischen Verbündeten.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/552520/header.jpg',
     '2018-03-27'),
    ('Far Cry 6',
     'Werde Guerilla-Kämpfer auf der Insel Yara. Befreie das Volk von Diktator Antón Castillo in einem riesigen Open-World-Shooter.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/2369390/header.jpg',
     '2022-10-07'),
    ('The Forest',
     'Überlebst du in einem dichten Wald voller Kannibalen? Baue, forsche und entdecke eine erschreckende Geschichte unter der Erdoberfläche.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/242760/header.jpg',
     '2018-04-30'),
    ('Subnautica: Below Zero',
     'Erkunde den eisigen Ozean eines fremden Planeten. Tauche in unbekannte Tiefen, baue Unterwasserstationen und löse ein galaktisches Geheimnis.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/848450/header.jpg',
     '2021-05-14'),
    ('Green Hell',
     'Überlebe im amazonischen Regenwald ohne Ausrüstung. Baue Unterkünfte, heile Wunden, besiege Parasiten und bewahre deinen Verstand.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/815370/header.jpg',
     '2019-09-05'),
    ('Metro 2033 Redux',
     'In den Tunneln der Moskauer Metro kämpft Artyom ums Überleben. Atmosphärischer Ego-Shooter basierend auf Dmitry Glukhovsky''s Roman.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/286690/header.jpg',
     '2014-08-26'),
    ('Warhammer: Vermintide 2',
     'Kooperativer Nahkampf-Slasher für vier Spieler. Kämpfe gegen Horden von Skaven und Chaos-Kriegern im düsteren Warhammer-Universum.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/552500/header.jpg',
     '2018-03-08');

-- Batch 5: Action, Souls-likes & Fighting Games
INSERT INTO games (title, description, image_url, release_date) VALUES
    ('Dark Souls II: Scholar of the First Sin',
     'Das zweite Kapitel der Souls-Saga in überarbeiteter Fassung. Erkundete die melancholische Welt Drangleic und besiege mächtige Könige.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/335300/header.jpg',
     '2015-04-02'),
    ('Guilty Gear: Strive',
     'Das modernste 2D-Kampfspiel auf dem Markt. Atemberaubende Anime-Grafik, tiefes Kampfsystem und ein epischer Metal-Soundtrack.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/1384160/header.jpg',
     '2021-06-11'),
    ('Blasphemous',
     'Ein brutales Metroidvania in einem düsteren spanisch-gotischen Setting. Pixel-Art auf höchstem Niveau mit grausamen Boss-Kämpfen.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/774361/header.jpg',
     '2019-09-10'),
    ('Blasphemous 2',
     'Der Nachfolger ist noch grösser und grausamer. Melinoe kehrt zurück in die Welt des ewigen Leidens mit neuen Waffen und Fähigkeiten.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/2114740/header.jpg',
     '2023-08-24'),
    ('Sifu',
     'Kung-Fu-Action auf höchstem Niveau. Du alterst bei jedem Tod, aber wirst weiser. Ein brutales, präzises Martial-Arts-Meisterwerk.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/2138710/header.jpg',
     '2023-03-28'),
    ('Neon White',
     'Ein rasanter Ego-Speedrunner-Shooter im Paradies. Besiege Dämonen mit Karten-basierten Waffen und breche Rekorde in jedem Level.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/1533420/header.jpg',
     '2022-06-16'),
    ('Monster Hunter Stories 2: Wings of Ruin',
     'Ein JRPG im Monster-Hunter-Universum. Schlüpfe in die Rolle eines Riders, brüte Monster-Eier aus und kämpfe rundenbasiert.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/1277400/header.jpg',
     '2021-07-09'),
    ('Katana ZERO',
     'Ein stylischer Neo-Noir-Plattformer. Du bist ein Samurai-Auftragskiller mit Zeitmanipulation – ein Treffer tötet, dich und den Feind.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/1109900/header.jpg',
     '2019-04-18'),
    ('Wo Long: Fallen Dynasty',
     'Souls-inspiriertes Action-RPG im mythologischen China der Han-Dynastie. Meistere das Deflect-System und besiege dämonische Feldherren.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/1703340/header.jpg',
     '2023-03-03'),
    ('Remnant II',
     'Ein kooperativer Third-Person-Shooter mit Souls-Elementen in prozedural generierten Welten. Jeder Run bietet neue Boss-Kombinationen.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/1282100/header.jpg',
     '2023-07-25'),
    ('Dead Space Remake',
     'Das Remake des Survival-Horror-Klassikers. Isaac Clarke kämpft auf der USG Ishimura gegen die grauenhaften Necromorphs. Absolut beängstigend.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/1693980/header.jpg',
     '2023-01-27'),
    ('Starfield',
     'Bethesdas erstes neues Universum seit 25 Jahren. Erkunde hunderte Planeten, baue Raumschiffe und suche nach uralten Artefakten im All.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/1716740/header.jpg',
     '2023-09-06'),
    ('Atomic Heart',
     'Ein Ego-Shooter in einer retrofuturistischen Sowjetunion, in der Roboter durchgedreht sind. Bizarre Welt, kraftvolles Kampfsystem.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/668580/header.jpg',
     '2023-02-21'),
    ('Hi-Fi Rush',
     'Ein rhythmus-basiertes Action-Spiel voller Musik. Alles im Spiel pulsiert zum Beat – kämpfe, weiche aus und rocke die Fabrik.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/1817230/header.jpg',
     '2023-01-25'),
    ('Hogwarts Legacy',
     'Lebe das Hogwarts-Abenteuer im 1800er-Jahrhundert. Erforsche das Schloss, lerne Zauber und entdecke ein dunkles Geheimnis in der Zauberwelt.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/990080/header.jpg',
     '2023-02-10'),
    ('Star Wars Jedi: Survivor',
     'Cal Kestis kehrt zurück. Fünf Jahre nach Fallen Order kämpft der Jedi auf der Flucht gegen das Imperium und sucht nach einer sicheren Zuflucht.',
      'https://cdn.cloudflare.steamstatic.com/steam/apps/1774580/header.jpg',
     '2023-04-28'),
    ('Warhammer 40,000: Space Marine 2',
     'Spiele als Ultra Marine Titus und kämpfe gegen endlose Tyraniden-Horden. Epische Schlachten in der Warhammer-40k-Welt. Gore pur.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/2183900/header.jpg',
     '2024-09-09'),
    ('Dragon''s Dogma 2',
     'Ein einzigartiges Action-RPG mit einem revolutionären Begleitersystem. Erkunde eine riesige Welt und besiege kolossale Monster als Arisen.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/2054970/header.jpg',
     '2024-03-22'),
    ('Palworld',
     'Fange und züchte Pals in einer offenen Welt voller Gefahren. Baue Fabriken, kämpfe gegen Wilderer und überlebe mit deinen Kreaturen.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/1623730/header.jpg',
     '2024-01-19'),
    ('Helldivers 2',
     'Kooperativer Third-Person-Shooter für Demokratie und Freiheit. Kämpfe als Helldiver gegen Bugs und Bots auf feindlichen Planeten.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/553850/header.jpg',
     '2024-02-08'),
    ('Black Myth: Wukong',
     'Ein cinematisches Action-RPG basierend auf der chinesischen Legende "Reise nach Westen". Atemberaubende Grafik und epische Boss-Kämpfe.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/2358720/header.jpg',
     '2024-08-20'),
    ('The Talos Principle',
     'Ein philosophisches Puzzle-Spiel. Als Roboter löst du hunderte Rätsel und hinterfragst Bewusstsein, freien Willen und die Natur der Existenz.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/257510/header.jpg',
     '2014-12-11'),
    ('Chicory: A Colorful Tale',
     'Du bist der Assistent einer legendären Malerin und benutzt ihren Pinsel, um die ganze Welt einzufärben. Herzerwärmendes Puzzle-Abenteuer.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/1123510/header.jpg',
     '2021-06-10'),
    ('Octopath Traveler',
     'Acht Reisende, acht Geschichten in einer wunderschönen HD-2D-Welt. Klassisches JRPG mit modernem Rundenklampfsystem und atemberaubender Musik.',
      'https://cdn.cloudflare.steamstatic.com/steam/apps/921570/header.jpg',
     '2018-07-13'),
    ('Octopath Traveler II',
     'Der Nachfolger mit nochmals verfeinerten Mechaniken und bewegenden Geschichten. Entdecke die Welt Solistia mit acht neuen Reisenden.',
      'https://cdn.cloudflare.steamstatic.com/steam/apps/1971650/header.jpg',
     '2023-02-24');

-- Batch 6: Indie-Perlen, Roguelikes & Narrative Games
INSERT INTO games (title, description, image_url, release_date) VALUES
    ('The Binding of Isaac: Rebirth',
     'Ein süchtig machendes Roguelike in einem düsteren Keller voller Monster. Hunderte von Items erschaffen verrückte Synergie-Kombinationen.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/250900/header.jpg',
     '2014-11-04'),
    ('Spelunky 2',
     'Das härteste und belohnendste Plattform-Roguelike. Jede Höhle birgt neue Gefahren und Geheimnisse – Permadeath zwingt dich zum Lernen.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/418530/header.jpg',
     '2021-08-12'),
    ('Rogue Legacy 2',
     'Erkunde eine sich verändernde Burg mit dem Erbe deiner Familie. Jeder Nachfahre hat einzigartige Traits – von Kurzsichtig bis Gigantisch.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/1253920/header.jpg',
     '2022-04-28'),
    ('Undertale',
     'Ein JRPG, in dem du niemanden töten musst. Erlebe eine herzerwärmende und subversive Geschichte über Freundschaft, Wahl und Empathie.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/391540/header.jpg',
     '2015-09-15'),
    ('Inscryption',
     'Ein Deck-Building-Roguelike voller dunkler Geheimnisse. Die Grenze zwischen Spiel und Wirklichkeit verschwimmt in diesem Meta-Horror-Erlebnis.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/1092790/header.jpg',
     '2021-10-19'),
    ('Omori',
     'Ein surreales Horror-RPG über Trauer, Schuld und psychische Gesundheit. Erkunde die bunten Traumwelten und die dunkle Realität dahinter.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/1150690/header.jpg',
     '2020-12-25'),
    ('What Remains of Edith Finch',
     'Erkunde das Haus der Familie Finch und entdecke das Schicksal jedes Familienmitglieds. Ein meisterhaftes interaktives Erlebnis über das Leben.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/501300/header.jpg',
     '2017-04-25'),
    ('GRIS',
     'Ein traumhaftes Plattformspiel ohne Text. Die junge Gris bewältigt ihren Kummer durch Farben und Musik in einer atemberaubenden Aquarell-Welt.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/683320/header.jpg',
     '2018-12-13'),
    ('Spiritfarer',
     'Du bist die Fährfrau der Toten. Bring Geister zu ihrem letzten Aufenthaltsort – ein sanftes, emotionales Cozy-Game über den Tod und das Loslassen.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/972660/header.jpg',
     '2020-08-18'),
    ('Unpacking',
     'Entpacke Kisten und ordne ein Leben. Dieses stille Puzzle-Spiel erzählt durch Gegenstände eine berührende Geschichte über Wachstum und Zuhause.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/1135690/header.jpg',
     '2021-11-02'),
    ('Brotato',
     'Du bist eine Kartoffel und kämpfst gegen Alien-Horden. Ein hektisches Arena-Roguelike, das mit einem einzigartigen Waffensystem überzeugt.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/1942280/header.jpg',
     '2023-11-08'),
    ('Loop Hero',
     'Deine Welt ist in einer Zeitschleife gefangen. Platziere Karten, um Terrain zu erschaffen, und schicke deinen Helden auf automatische Reisen.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/1282730/header.jpg',
     '2021-03-04'),
    ('The Forgotten City',
     'Eine Zeitschleife in einem antiken römischen Stadtmodell. Entdecke, warum ein mysteriöses Gesetz die Bevölkerung in Gold verwandelt.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/1281930/header.jpg',
     '2021-07-28'),
    ('Eastward',
     'Ein JRPG-Abenteuer in einer postapokalyptischen Welt. John und Sam reisen mit dem Zug durch eindrucksvolle Pixel-Art-Städte voller Geheimnisse.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/977880/header.jpg',
     '2021-09-16'),
    ('Nobody Saves the World',
     'Verwandle dich in über 15 verschiedene Formen – von Pferd bis Roboter. Ein cleveres Action-RPG mit kreativem Klassen-Mischsystem.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/1432370/header.jpg',
     '2022-01-18'),
    ('Signalis',
     'Ein Survival-Horror aus Spielerperspektive in einer retrofuturistischen Dystopie. Geprägt von Silent-Hill-Atmosphäre und Science-Fiction-Lore.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/1262350/header.jpg',
     '2022-10-27'),
    ('Cult of the Lamb',
     'Baue deinen eigenen Kult auf und opfere deine Anhänger. Ein niedliches Roguelite kombiniert mit Aufbausimulation und dunklem Humor.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/1313140/header.jpg',
     '2022-08-11'),
    ('Dredge',
     'Du bist ein Fischer in einer düsteren Küstenregion voller Geheimnisse. Verkaufe Fische bei Tag, fliehe vor dem Grauen bei Nacht. Lovecraftian.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/1562430/header.jpg',
     '2023-03-30'),
    ('Sea of Stars',
     'Ein Pixel-Art-JRPG, das von den Klassikern wie Chrono Trigger inspiriert ist. Zwei Kinder des Sonnenwende kämpfen gegen das Böse im Universum.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/1380220/header.jpg',
     '2023-08-29'),
    ('Dave the Diver',
     'Tauche tagsüber und führe abends ein Sushi-Restaurant. Eine überraschend tiefe Mischung aus Abenteuer, Management und kulinarischer Freude.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/1868140/header.jpg',
     '2023-06-28'),
    ('Cocoon',
     'Trage Welten als Kugeln auf deinem Rücken und löse Rätsel, die die Dimensionen verschachteln. Minimalistisch geniales Puzzle-Design.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/1497440/header.jpg',
     '2023-09-29'),
    ('Pizza Tower',
     'Ein wahnsinnig schnelles Plattformspiel im Stil von Wario Land. Peppino Spaghetti rast durch verrückte Level und muss seinen Pizzaladen retten.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/2231450/header.jpg',
     '2023-01-26'),
    ('The Talos Principle 2',
     'Der Nachfolger des Philosophie-Puzzlespiels. In einer Welt, in der Menschen ausgestorben sind, stellt sich ein Roboter die grossen Fragen.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/835780/header.jpg',
     '2023-11-02'),
    ('Doki Doki Literature Club Plus!',
     'Was als niedliche Visual Novel beginnt, entpuppt sich als erschreckender Meta-Horror. Kein normales Spiel – Vorsicht ist geboten.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/1388880/header.jpg',
     '2021-06-30'),
    ('A Short Hike',
     'Ein entspanntes Abenteuer auf einem kleinen Berg. Klettere, gleite und entdecke liebenswürdige Charaktere in einer wunderschönen Pixel-Welt.',
      'https://cdn.cloudflare.steamstatic.com/steam/apps/1055540/header.jpg',
      '2019-07-30');

-- Batch 7: 100 neue verifizierte Spiele
INSERT INTO games (title, description, image_url, release_date) VALUES
    ('Tales of ARISE',
     'Ein mitreissendes Action-RPG von Bandai Namco. Alphen und Shionne kämpfen für die Befreiung eines versklavten Volkes in einer geteilten Welt.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/740130/header.jpg',
     '2021-09-10'),
    ('Dragon Quest XI S: Echoes of an Elusive Age',
     'Das jüngste Meisterwerk der Dragon-Quest-Reihe. Begleite den Helden auf einer epischen Reise durch die Welt von Erdrea, um sein Schicksal zu erfüllen.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/960170/header.jpg',
     '2019-09-27'),
    ('Ys VIII: Lacrimosa of DANA',
     'Adol Christin strandet auf einer verfluchten Insel und gründet ein Lager mit anderen Überlebenden. Ein packender Action-RPG-Mix aus Erkundung und Kampf.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/579180/header.jpg',
     '2018-06-26'),
    ('Ni no Kuni II: Revenant Kingdom',
     'Der König Evan wird entthront und baut ein neues Königreich auf. Wunderschönes Action-RPG im Studio-Ghibli-Stil mit farbenprächtigem Weltdesign.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/589360/header.jpg',
     '2018-03-23'),
    ('Grim Dawn',
     'Ein dunkles Action-RPG im postapokalyptischen Viktorianischen Zeitalter. Tief verwurzeltes Charaktersystem mit dualen Klassen und unzähligen Build-Möglichkeiten.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/219990/header.jpg',
     '2016-02-25'),
    ('Dragon Age: The Veilguard',
     'Rook führt ein Team aus Spezialisten in der Welt von Thedas. Ein modernes BioWare-RPG voller Entscheidungen, Verbündeter und uralter dämonischer Bedrohungen.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/1845910/header.jpg',
     '2024-10-31'),
    ('Horizon Forbidden West Complete Edition',
     'Aloy erkundet den gefährlichen amerikanischen Westen voller feindlicher Maschinen und verlorener Zivilisationen. Atemberaubende Grafik und tiefe Lore.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/2420110/header.jpg',
     '2024-03-21'),
    ('God of War Ragnarök',
     'Kratos und Atreus stehen vor der nordischen Apokalypse. Ein cinematisches Meisterwerk mit spektakulären Kämpfen gegen Götter und Riesen.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/2322010/header.jpg',
     '2024-09-19'),
    ('Halo Infinite',
     'Master Chief kehrt zurück. Der Spartan kämpft auf dem Ringwelt-Halo gegen die Verbannten in einer offenen Welt mit klassischem Halo-Gunplay.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/1240440/header.jpg',
     '2021-12-08'),
    ('Halo: The Master Chief Collection',
     'Sechs Halo-Spiele in einem Bundle. Erlebe die gesamte Master-Chief-Saga in remastered Grafik mit vollständigem Online-Multiplayer.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/976730/header.jpg',
     '2019-12-03'),
    ('Hunt: Showdown 1896',
     'Ein einzigartiger PvPvE-Extraction-Shooter im Sumpf von Louisiana. Jage Monster, sammle Beute – und überlebe andere Kopfgeldjäger auf dem Rückweg.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/594650/header.jpg',
     '2019-08-27'),
    ('DayZ',
     'Das originale Open-World-Survival-Spiel. Kämpfe in Chernarus ums Überleben gegen Zombies, Hunger, Kälte – und andere skrupellose Spieler.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/221100/header.jpg',
     '2018-12-13'),
    ('Hell Let Loose',
     'Realistischer WW2-Taktik-Shooter für 100 Spieler. Koordinierte Infanterie, Panzer und Artillerie kämpfen in historischen Schlachten um die Frontlinie.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/686810/header.jpg',
     '2021-07-27'),
    ('Ready or Not',
     'Du führst ein Elite-SWAT-Team in hochriskante taktische Einsätze. Brutaler, realistischer Taktik-Shooter mit intensivem Slow-is-Smooth-Gameplay.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/1144200/header.jpg',
     '2023-12-13'),
    ('Insurgency: Sandstorm',
     'Realistischer Taktik-Shooter in modernen Konfliktgebieten. Kein HUD, kein Lebensbalken – ein Treffer kann tödlich sein. Für Veteranen.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/581320/header.jpg',
     '2018-12-12'),
    ('Battlefield 1',
     'Der Erste Weltkrieg wie nie zuvor. Erlebe Schützengräben, Panzer, Kavallerie und Luftkämpfe in einem der stimmungsvollsten Multiplayer-Shooter aller Zeiten.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/1238810/header.jpg',
     '2016-10-21'),
    ('SOMA',
     'Ein Sci-Fi-Horror-Erlebnis unter dem Ozean. Die philosophischen Fragen über Bewusstsein und Identität sind erschreckender als jedes Monster.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/282140/header.jpg',
     '2015-09-22'),
    ('Amnesia: The Bunker',
     'Du bist allein in einem WW1-Bunker mit einem hungrigen Monster. Kein sicherer Ort, kein Skript – ein atmosphärisches Survival-Horror-Meisterwerk.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/1944430/header.jpg',
     '2023-06-06'),
    ('The Evil Within 2',
     'Detective Castellanos taucht erneut in eine alptraumhafte virtuelle Realität ein, um seine Tochter zu retten. Grossartiger Action-Horror-Mix.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/601430/header.jpg',
     '2017-10-13'),
    ('Outlast 2',
     'Als Journalist Blake Langermann erforschst du eine fanatische Sekte in Arizona. Kein Kämpfen, nur Rennen und Verstecken vor dem purem Terror.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/414700/header.jpg',
     '2017-04-25'),
    ('Alan Wake 2',
     'Der Bestsellerautor Alan Wake steckt in einer dunklen Dimension fest. Ein surrealer Psycho-Thriller mit cinematischer Inszenierung und kreativem Storytelling.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/1903780/header.jpg',
     '2023-10-27'),
    ('Resident Evil 3',
     'Jill Valentine flieht durch Raccoon City – verfolgt vom unaufhaltsamen Nemesis. Das Remake des Klassikers mit packenden Actionsequenzen.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/952060/header.jpg',
     '2020-04-03'),
    ('Resident Evil 7 Biohazard',
     'Ein Neuanfang für die RE-Reihe: Egoperspektive, echte Angst, Southern-Gothic-Atmosphäre. Ethan Winters sucht seine Frau in einem Albtraum-Anwesen.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/418370/header.jpg',
     '2017-01-24'),
    ('Dead by Daylight',
     'Ein asymmetrischer Multiplayer-Horror: Vier Überlebende versuchen zu entkommen, ein Killer versucht sie zu opfern. Mit ikonischen Horrorfiguren aus Film und TV.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/381210/header.jpg',
     '2016-06-14'),
    ('Sid Meier''s Civilization VI',
     'Baue eine Zivilisation, die den Test der Zeit besteht. Forsche, handle, kämpfe und diplomatiere dich zum Sieg in diesem legendären Rundenstrategie-Spiel.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/289070/header.jpg',
     '2016-10-21'),
    ('Age of Empires II: Definitive Edition',
     'Die ultimative Neuauflage des Klassikers mit neuen Kampagnen, 4K-Grafik und verbessertem Multiplayer. Das beste Echtzeit-Strategiespiel aller Zeiten.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/813780/header.jpg',
     '2019-11-14'),
    ('Desperados III',
     'Meisterhaftes Echtzeit-Taktikspiel im Wilden Westen. Führe eine Gruppe von Spezialisten durch raffinierte Missionen mit viel Sandkasten-Kreativität.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/610370/header.jpg',
     '2020-06-16'),
    ('Shadow Tactics: Blades of the Shogun',
     'Leite fünf Ninja-Spezialisten durch das feudale Japan des 17. Jahrhunderts. Taktisches Meisterwerk mit perfektem Schwierigkeitsgrad und kreativem Leveldesign.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/489520/header.jpg',
     '2016-12-06'),
    ('Two Point Hospital',
     'Baue und manage absurde Krankenhäuser voller komischer Krankheiten. Ein humorvoller Nachfolger des Theme-Hospital-Klassikers mit endloser Tiefe.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/535930/header.jpg',
     '2018-08-30'),
    ('Planet Zoo',
     'Baue den Zoo deiner Träume. Pflege Hunderte von Tierarten, gestalte natürliche Gehege und manage eine erfolgreiche Anlage mit ethischem Tierschutz.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/703080/header.jpg',
     '2019-11-05'),
    ('Planet Coaster',
     'Das ultimative Freizeitpark-Sandbox-Spiel. Bau atemberaubende Achterbahnen, schaffe unvergessliche Erlebnisse und bringe deine kreative Vision zum Leben.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/493340/header.jpg',
     '2016-11-17'),
    ('Jurassic World Evolution 2',
     'Manage echte Dinosaurier-Parks mit wissenschaftlicher Präzision. Züchte über 75 Dinosaurierarten, handle mit Hybridgenen und halte die Besucher sicher.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/1244460/header.jpg',
     '2021-11-09'),
    ('Microsoft Flight Simulator 2020',
     'Fliege über die gesamte Erde in nie dagewesener Detailtreue. Der Flugsimulator der neuen Generation mit echten Wetterdaten und fotorealistischer Welt.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/1250410/header.jpg',
     '2020-08-18'),
    ('Euro Truck Simulator 2',
     'Werde König der Autobahn und fahre quer durch Europa. Liefere Frachten in über 70 europäische Städte und baue dein eigenes Logistikunternehmen auf.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/227300/header.jpg',
     '2012-10-19'),
    ('American Truck Simulator',
     'Erkunde die weiten Highways der USA in einem riesigen Truck. Mit authentischen Routen durch Californien, Arizona, New Mexico und vielen weiteren Bundesstaaten.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/270880/header.jpg',
     '2016-02-03'),
    ('Space Engineers',
     'Baue Raumschiffe, Raumstationen und Planeten-Basen. Ein Ingenieur-Sandbox-Spiel mit realistischer Physik und unendlichen Möglichkeiten im Weltall.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/244850/header.jpg',
     '2019-02-28'),
    ('Kerbal Space Program 2',
     'Baue Raketen und erkunde das Universum mit den kleinen grünen Kerbal-Astronauten. Tiefe Physik-Simulation trifft auf Sandbox-Kreativität.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/954850/header.jpg',
     '2023-02-24'),
    ('Astroneer',
     'Erkunde prozedural generierte Planeten, baue Basen und terraformiere fremde Welten. Ein entspanntes, farbenfrohes Sci-Fi-Survival-Abenteuer im Koop.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/361420/header.jpg',
     '2019-12-16'),
    ('Hardspace: Shipbreaker',
     'Zerlege ausrangierte Raumschiffe Stück für Stück in der Schwerelosigkeit. Ein einzigartiges Puzzle-Handwerk-Spiel mit einer kritischen Story über Arbeiterrechte.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/1161580/header.jpg',
     '2022-05-24'),
    ('Scrap Mechanic',
     'Baue verrückte Fahrzeuge und Maschinen aus Schrott. Eine kreative Mehrspieler-Sandbox, in der Physik und Logik zu riesigen mechanischen Kreationen führen.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/387990/header.jpg',
     '2020-09-10'),
    ('BeamNG.drive',
     'Die realistischste Fahrzeugphysik-Simulation der Welt. Crash-Tests, Offroad-Abenteuer und Stunt-Fahrten mit deformierbaren Fahrzeugen in offenen Welten.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/284160/header.jpg',
     '2015-08-03'),
    ('Teardown',
     'Plane den perfekten Raub in einer vollständig zerstörbaren Voxel-Welt. Durchbreche Wände, baue Rampen aus Trümmern und entkampe mit der Beute.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/1167630/header.jpg',
     '2022-04-21'),
    ('V Rising',
     'Du bist ein erwachender Vampir und baust dein Schloss. Jage Beute, trinke Blut, erforsche eine dunkle Welt und vermeide das tödliche Sonnenlicht.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/1604030/header.jpg',
     '2023-05-08'),
    ('Core Keeper',
     'Grabe tief in eine unterirdische Welt voller Geheimnisse, Bosse und Ressourcen. Ein entspanntes Koop-Survival mit Crafting und Farming-Elementen.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/1621690/header.jpg',
     '2022-03-08'),
    ('Raft',
     'Überlebe auf einem kleinen Floss mitten im Ozean. Baue dein Floss aus, fische Ressourcen aus dem Wasser und erkunde mysteriöse Inseln mit Freunden.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/648800/header.jpg',
     '2022-06-20'),
    ('The Planet Crafter',
     'Terraformiere einen fremden Planeten alleine oder im Koop. Baue Maschinen, die Atmosphäre erzeugen, und verwandle eine Ödnis in eine lebendige Welt.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/1284190/header.jpg',
     '2024-03-07'),
    ('Lethal Company',
     'Sammle Schrott auf verlassenen, von Monstern heimgesuchten Monden für eine mysteriöse Firma. Das gruseligste und lustigste Koop-Spiel des Jahres.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/1966720/header.jpg',
     '2023-10-23'),
    ('Slime Rancher',
     'Betreibe eine Farm auf einem fremden Planeten und sammle süsse, bunte Slimes. Ein entspanntes Abenteuer voller Geheimnisse und entzückender Kreaturen.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/433340/header.jpg',
     '2017-08-01'),
    ('Slime Rancher 2',
     'Der Nachfolger der Slime-Farm-Abenteuer auf der neuen Insel Rainbow Island. Entdecke neue Slime-Arten und ein riesiges Höhlensystem voller Geheimnisse.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/1657630/header.jpg',
     '2022-09-22'),
    ('Stranded Deep',
     'Du überlebst einen Flugzeugabsturz im Pazifik. Baue Unterstände, fische, tauche nach Ressourcen und bekämpfe riesige Haie und Kraken.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/313120/header.jpg',
     '2020-04-17'),
    ('Enshrouded',
     'Baue und erkunde eine Welt, die von einem magischen Nebel – dem Shroud – bedeckt ist. Ein spannendes Survival-RPG mit umfangreichem Crafting und Basisbau.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/1203620/header.jpg',
     '2024-01-24'),
    ('Noita',
     'Jeder Pixel ist physisch simuliert. Ein magisches Roguelike, in dem du mächtige Zauberstäbe kombinierst und dabei Wälder in Brand setzt, Seen leerpumpst und dich selbst sprengst.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/881100/header.jpg',
     '2020-09-24'),
    ('Balatro',
     'Ein hypnotisches Poker-Roguelike voller perverser Synergieen. Baue ein Deck aus Jokers und Power-Ups, das die Regeln des Pokerspiels komplett neu erfindet.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/2379780/header.jpg',
     '2024-02-20'),
    ('Against the Storm',
     'Ein Roguelite-Stadtbau-Spiel im ewigen Regen. Baue Siedlungen für Biber, Echsen und Menschenvölker – und schaffe es, bevor ein Sturm alles vernichtet.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/1359090/header.jpg',
     '2023-12-08'),
    ('Dicey Dungeons',
     'Ein charmantes Würfel-Roguelike mit sechs einzigartigen Charakteren. Kämpfe durch bunte Kerker mit würfelbasierten Fähigkeiten und taktischen Deckbuilding-Elementen.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/861540/header.jpg',
     '2019-08-13'),
    ('Streets of Rage 4',
     'Die Legende kehrt zurück. Axel, Blaze und neue Kämpfer reinigen die Stadt von Schurken. Das beste Beat-em-up seit Jahrzehnten mit wunderschöner Hand-Art.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/985890/header.jpg',
     '2020-04-30'),
    ('Teenage Mutant Ninja Turtles: Shredder''s Revenge',
     'Die vier Turtles kehren in einem Retro-Beat-em-up zurück. Bis zu 6 Spieler im Koop zerdreschen Foot-Soldaten in einer Liebeserklärung an die 80er-Zeichentrickserie.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/1361510/header.jpg',
     '2022-06-16'),
    ('Crash Bandicoot N. Sane Trilogy',
     'Alle drei Crash-Bandicoot-Spiele wunderschön remastert. Spiele die ikonischen PlayStation-1-Plattformer in voller HD-Grafik mit verbessertem Gameplay.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/731490/header.jpg',
     '2018-06-29'),
    ('Rayman Legends',
     'Eines der schönsten Plattformspiele aller Zeiten. Rayman und seine Freunde kämpfen durch wunderschöne handgezeichnete Welten mit innovativen Musikleveln.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/260230/header.jpg',
     '2013-08-30'),
    ('Shovel Knight: Treasure Trove',
     'Das komplette Shovel-Knight-Paket mit vier spielbaren Kampagnen. Einer der besten Plattformer der modernen Ära, inspiriert von NES-Klassikern.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/250760/header.jpg',
     '2014-06-26'),
    ('Hotline Miami',
     'Ein brutales, hypnotisches Top-Down-Actionspiel mit einem Neon-Soundtrack. Töte alle in einem Raum mit einem Treffer – und stirb genauso schnell.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/219150/header.jpg',
     '2012-10-23'),
    ('Hotline Miami 2: Wrong Number',
     'Der Abschluss der Hotline-Miami-Saga. Noch mehr brutale Top-Down-Action mit multiplen Charakteren und einer kryptischen, nicht-linearen Erzählstruktur.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/274170/header.jpg',
     '2015-03-10'),
    ('Human: Fall Flat',
     'Steuere einen wackeligen Traumwandler durch physikbasierte Rätselwelten. Alleine oder mit bis zu acht Spielern im chaotischen Online-Koop.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/477160/header.jpg',
     '2016-07-22'),
    ('Gang Beasts',
     'Schlüpfe in eine seltsame Welt aus weichen Gelatine-Charakteren und kämpfe in chaotischen Multiplayer-Brawls auf absurden Schauplätzen.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/285900/header.jpg',
     '2017-12-12'),
    ('Moving Out',
     'Das chaotischste Umzugsunternehmen der Welt. Transportiere Möbel durch absurde Level – mit oder gegen Physik und Vernunft – im Sofa- oder Online-Koop.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/996770/header.jpg',
     '2020-04-28'),
    ('Overcooked! 2',
     'Das schönste Streit-Spiel für Freunde und Familie. Koche in chaotischen Küchen gemeinsam Mahlzeiten – bevor die Zeit abläuft und alles anbrennt.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/728880/header.jpg',
     '2018-08-07'),
    ('Geometry Dash',
     'Ein rasanter Rhythmus-Plattformer, der deine Reflexe auf die ultimative Probe stellt. Tausende nutzergenerierte Level und ein süchtig machender Soundtrack.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/322170/header.jpg',
     '2014-12-22'),
    ('Crash Bandicoot 4: It''s About Time',
     'Der direkte Nachfolger der Original-Trilogie. Crash und Coco reisen durch Dimensionen und Zeitlinien in einem modernen Plattformer mit knackigem Schwierigkeitsgrad.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/1378990/header.jpg',
     '2021-10-19'),
    ('Trine 4: The Nightmare Prince',
     'Die drei Helden Amadeus, Pontius und Zoya kehren in einem wunderschönen Puzzle-Plattformer zurück. Magische Physik-Rätsel in einer märchenhaften Welt.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/690640/header.jpg',
     '2019-10-08'),
    ('Broforce',
     'Befreie die Welt als pixelhafte Parodien auf Actionfilm-Helden wie Rambo und Terminator. Explosives, schnelles Side-Scroller-Chaos für bis zu vier Spieler.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/274190/header.jpg',
     '2015-10-15'),
    ('Warhammer 40,000: Darktide',
     'Kämpfe als Teil einer Truppe gegen endlose Schwärme von Ketzern in einer düsteren Hive-Stadt. Der духовный Nachfolger von Vermintide im 40k-Universum.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/1361210/header.jpg',
     '2022-11-30'),
    ('New World: Aeternum',
     'Ein MMORPG auf der mysteriösen Insel Aeternum. Kämpfe in Echtzeit, sammle Ressourcen, schliesse Fraktionen an und erkunde eine riesige, übernatürliche Welt.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/1063730/header.jpg',
     '2021-09-28'),
    ('Lost Ark',
     'Ein rasantes Action-MMORPG voller Dungeons, Raids und Welterkundung. Spektakuläre isometrische Kämpfe mit einer riesigen Charakterauswahl und tiefer Progression.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/1599340/header.jpg',
     '2022-02-11'),
    ('The Elder Scrolls Online',
     'Erkunde Tamriel in einem riesigen MMORPG. Alle Regionen aus den Elder-Scrolls-Spielen in einer Welt – Questlines, Dungeons und PvP für tausende Stunden.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/306130/header.jpg',
     '2014-04-04'),
    ('Black Desert Online',
     'Ein atemberaubend schönes Action-MMORPG mit dem flüssigsten Kampfsystem des Genres. Komplexes Lebensfertigkeits-System und endlose Charakteranpassung.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/582660/header.jpg',
     '2016-03-03'),
    ('The Witness',
     'Erkunde eine mysteriöse Insel voller Rätsel. Keine Erklärungen, keine Tutorials – nur 700 Panel-Puzzles die dein Verständnis der Welt immer tiefer herausfordern.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/210970/header.jpg',
     '2016-01-26'),
    ('Night in the Woods',
     'Mae Borowski kehrt in ihre Heimatstadt zurück und entdeckt, dass sich etwas Seltsames verändert hat. Ein warmherziges, melancholisches Coming-of-Age-Abenteuer.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/481510/header.jpg',
     '2017-02-21'),
    ('Oxenfree',
     'Eine Gruppe Teenager öffnet versehentlich ein Geisterportal auf einer verlassenen Insel. Ein atmosphärisches Narrativ-Abenteuer mit bahnbrechenden Dialogsystemen.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/388880/header.jpg',
     '2016-01-15'),
    ('Return to Monkey Island',
     'Ron Gilbert kehrt zu seiner legendären Piratenkomödie zurück. Guybrush Threepwood sucht endlich das Geheimnis von Monkey Island in einer witzigen Point-and-Click-Adventure.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/2060130/header.jpg',
     '2022-09-19'),
    ('Pentiment',
     'Ein narratives Adventure in einem mittelalterlichen bayerischen Kloster. Dein Künstler untersucht über Jahrzehnte hinweg eine Mordserie in handgezeichneter Buchmalerei.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/1205520/header.jpg',
     '2022-11-15'),
    ('F1 24',
     'Die neueste Ausgabe der offiziellen Formel-1-Simulation. Erlebe alle Teams, Fahrer und Strecken der Saison 2024 in atemberaubender Simulation.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/2488620/header.jpg',
     '2024-05-31'),
    ('Need for Speed Unbound',
     'Renne durch Lakeshore City in einem stylischen Arcade-Racer mit einzigartiger Comic-Grafik. Fahre in Turnieren gegen die besten Streetracer der Stadt.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/1846380/header.jpg',
     '2022-12-02'),
    ('Mortal Kombat 11',
     'Das brutalste Mortal Kombat aller Zeiten mit zeitreise-basierter Story. Cineastische Fatalities, ein riesiger Charakter-Roster und tiefes Kampfsystem.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/976310/header.jpg',
     '2019-04-23'),
    ('Injustice 2',
     'DC-Superhelden und -Schurken kämpfen in einem epischen Prügelspiel. Anpassbares Ausrüstungssystem, packende Story und einer der besten NetherRealm-Fighter.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/627270/header.jpg',
     '2017-11-14'),
    ('Final Fantasy XIV Online',
     'Das beste MMORPG auf dem Markt. Erkunde Eorzea mit einer preisgekrönten Hauptstory, epischen Raids, kreativem Housing und einer der freundlichsten Gaming-Communitys.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/39210/header.jpg',
     '2013-08-27'),
    ('Lightyear Frontier',
     'Farme auf fremden Planeten mit einem Mech-Anzug. Ein entspanntes Koop-Abenteuer voller farbenfroher Biome, freundlicher Aliens und kreativen Basisbau-Optionen.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/1677110/header.jpg',
     '2024-03-19'),
    ('Two Point Campus',
     'Baue und manage eine Universität für absurde Studienfächer wie Ritterschaft und Kochkunst. Der humorvolle Nachfolger von Two Point Hospital mit frischem Setting.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/1649080/header.jpg',
     '2022-08-09'),
    ('Humankind',
     'Eine komplexe Alternative zu Civilization: Forme eine einzigartige Zivilisation aus sechzig Kulturen. Tiefes diplomatisches und militärisches System über Tausende Jahre.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/1124300/header.jpg',
     '2021-08-17'),
    ('The Outlast Trials',
     'Das erste Koop-Spiel der Outlast-Reihe. Ein bis vier Spieler überleben brutale Experimente in einer kalten-Kriegs-Einrichtung voller psychologischen Terrors.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/1506550/header.jpg',
     '2024-03-05'),
    ('Resident Evil 4 Remake',
     'Leon S. Kennedy rettet die Präsidenten-Tochter in einem spanischen Dorf voller infizierter Dorfbewohner. Das Remake des besten Action-Horror-Spiels aller Zeiten.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/2050650/header.jpg',
     '2023-03-24'),
    ('Guild Wars 2',
     'Ein MMORPG, das die Konventionen des Genres bricht. Kein monatliches Abo, dynamische Events statt statischer Quests und ein einzigartiges Charakter-Progression-System.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/1284210/header.jpg',
     '2015-08-29'),
    ('Farming Simulator 22',
     'Lebe das Leben eines modernen Landwirts. Bestelle Felder, züchte Tiere, manage Finanzen und nutze über 400 lizenzierte Landmaschinen in einem realistischen Setting.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/1248130/header.jpg',
     '2021-11-22'),
    ('DIRT 5',
     'Offroad-Racing-Action auf der ganzen Welt. Fahre durch Schnee, Schlamm, Eis und Sand in atemberaubenden Fahrzeugen mit Arcade-Handling und spektakulären Wetterbedingungen.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/1038250/header.jpg',
     '2020-11-06'),
    ('Steep',
     'Erlebe den ultimativen Wintersport-Playground in den Alpen. Ski, Snowboard, Wingsuit oder Schlitten – erkunde einen riesigen, nahtlosen Berg im Multiplayer.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/460920/header.jpg',
     '2016-12-02'),
    ('Gunfire Reborn',
     'Ein Roguelite-Ego-Shooter mit RPG-Elementen und niedlichen Tiercharakteren. Kombiniere mächtige Waffen und Fähigkeiten in immer verrückteren Build-Synergien.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/1217060/header.jpg',
     '2021-11-18'),
    ('Neon Abyss',
     'Ein roguelite Plattform-Shooter im neon-beleuchteten Dungeon voller Items und Götter-Power-Ups. Beschwöre Begleiter, bringe Eier zum Schlüpfen und werde unaufhaltsam.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/1138570/header.jpg',
     '2020-07-14'),
    ('Bloodstained: Ritual of the Night',
     'Das spirituelle Castlevania-Nachfolgespiel von Koji Igarashi. Miriam kämpft in einem von Dämonen befallenen Schloss und absorbiert deren Kräfte durch Scherben.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/692850/header.jpg',
     '2019-06-18'),
    ('Axiom Verge 2',
     'Ein Solo-Metroidvania das Welten und Realitäten verbindet. Erkunde mysteriöse Ruinen, beherrsche fremdartige Technologie und entdecke, wer du wirklich bist.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/946030/header.jpg',
     '2021-08-11'),
    ('Vampyr',
     'Du bist ein Arzt und Vampir im London von 1918. Jagst du Bürger für Blut und Macht oder schützt du sie? Deine Entscheidungen verändern die Welt dauerhaft.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/427290/header.jpg',
     '2018-06-05'),
    ('The Medium',
     'Ein psychologischer Horror-Thriller von den Machern der Observer-Serie. Reise gleichzeitig durch die reale und die Geisterwelt und löse ein dunkles Familiengeheimnis.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/1293160/header.jpg',
     '2021-01-28');

-- Batch 8: Aktuelle Games 2024 / 2025 / 2026
INSERT INTO games (title, description, image_url, release_date) VALUES
    ('ANIMAL WELL',
     'Ein rätselhaftes Metroidvania in einer dunklen, biolumineszenten Welt. Erkunde verborgene Gänge, löse clevere Umgebungsrätsel und entdecke ein tiefes Geheimnis in diesem atmosphärischen Indie-Meisterwerk.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/813230/header.jpg',
     '2024-05-09'),
    ('Nine Sols',
     'Ein düsteres Action-Plattformspiel im taoistisch-inspirierten Cyberpunk-Setting. Präzise Parrierungskämpfe gegen Sols und Dämonen – mit einer tiefgründigen Geschichte über Vergänglichkeit und Rebellion.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/1809540/header.jpg',
     '2024-06-29'),
    ('Dungeons of Hinterberg',
     'Erkunde idyllische Alpendörfer und bezwinge monster-gefüllte Dungeons als Touristin Luisa. Ein charmantes Action-RPG mit sozialem Leben am Tag, spannenden Rätseln und zauberhafter österreichischer Atmosphäre.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/1983260/header.jpg',
     '2024-07-18'),
    ('Flintlock: The Siege of Dawn',
     'Semiarid-Fantasy-Action-RPG, in dem eine Soldatin und ein Fuchsdämon gemeinsam gegen die Götter kämpfen. Explosives Kampfsystem, offene Welt und epische Mythologie in einer einzigartigen Fantasy-Umgebung.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/1832040/header.jpg',
     '2024-07-18'),
    ('The Plucky Squire',
     'Ein niedliches Action-Adventure, in dem du als Buchheld aus deinem 2D-Bilderbuch in die 3D-Welt springst. Kreatives Gameplay mit herzerwärmender Geschichte und wunderschönem Grafikstil.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/1627570/header.jpg',
     '2024-09-17'),
    ('Metaphor: ReFantazio',
     'Das neueste JRPG-Meisterwerk von Studio Zero. In einer politischen Fantasy-Welt beeinflusst du die Königswahl durch Reisen, Beziehungen und packende Kämpfe. Atemberaubendes Art-Design und tiefe Story.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/2679460/header.jpg',
     '2024-10-11'),
    ('Indiana Jones and the Great Circle',
     'Du bist Indiana Jones auf einer weltumspannenden Abenteuerreise voller Rätsel, Fallen und mächtiger Feinde. Ein cinematisches Ego-Abenteuer von MachineGames mit Peitschenaction in historischen Schauplätzen.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/2677660/header.jpg',
     '2024-12-09'),
    ('Path of Exile 2',
     'Der lang erwartete Nachfolger des komplexesten Action-RPGs aller Zeiten. Sechs neue Klassen, überarbeitetes Kampfsystem und eine neue dunkle Welt voller brutaler Feinde und tausenden Build-Möglichkeiten.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/2694490/header.jpg',
     '2024-12-06'),
    ('Sniper Elite: Resistance',
     'Scharfschützen-Taktik im besetzten Frankreich des Zweiten Weltkriegs. Infiltriere feindliche Stellungen, sabotiere Waffenprogramme und erlege Ziele mit präzisen Langstrecken-Schüssen in der größten Map-Serie.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/2169200/header.jpg',
     '2025-01-30'),
    ('Kingdom Come: Deliverance II',
     'Henry kehrt zurück in ein noch epischeres mittelalterliches Böhmen. Das Sequel des realistischen RPGs bietet eine grössere Welt, tiefere Kampfmechaniken und eine emotionale Fortsetzung seiner Geschichte.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/1771300/header.jpg',
     '2025-02-04'),
    ('Avowed',
     'Ein First-Person-RPG in der Welt der Pillars-of-Eternity-Reihe. Erkunde die Living Lands als kaiserlicher Botschafter und entdecke das Geheimnis einer mysteriösen Seuche mit mächtigen Zaubersprüchen und Waffen.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/2457220/header.jpg',
     '2025-02-18'),
    ('Like a Dragon: Pirate Yakuza in Hawaii',
     'Goro Majima ist zurück – diesmal als Pirat auf Hawaii. Ein verrücktes Action-Spinoff der Yakuza-Reihe mit epischen Seeschlachten, absurdem Humor und der gewohnten melodramatischen Yakuza-Intensität.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/3061810/header.jpg',
     '2025-02-21'),
    ('Monster Hunter Wilds',
     'Die nächste Generation der Monster-Hunter-Reihe. Erkunde atemberaubend schöne, dynamische Ökosysteme mit lebendigen Nahrungsketten und jage riesige Monster in einer Welt voller überraschender Gefahren.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/2246340/header.jpg',
     '2025-02-28'),
    ('Split Fiction',
     'Das neue Koop-Meisterwerk von Hazelight Studios. Zwei Schriftstellerinnen stecken in den Welten ihrer Bücher fest und müssen zusammenarbeiten – von Science-Fiction bis Fantasy, jedes Kapitel ein neues Abenteuer.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/2001120/header.jpg',
     '2025-03-06'),
    ('Witchfire',
     'Ein dunkler Roguelite-Ego-Shooter in einer düsteren Fantasy-Welt voller Hexen und Dämonen. Kämpfe als Hexenjäger, baue mächtige Arkanzauber auf und meistere prozedural generierte Missionen im göttlichen Fegefeuer.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/3156770/header.jpg',
     '2025-03-06'),
    ('Assassin''s Creed Shadows',
     'Erkunde das feudale Japan als Naoe, eine flinke Shinobi-Assassinin, und Yasuke, einen historischen Samurai. Zwei komplett unterschiedliche Spielstile, dynamische Jahreszeiten und eine packende Open World.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/3159330/header.jpg',
     '2025-03-20'),
    ('Atomfall',
     'Du erwachst in einem mysteriösen britischen Quarantänegebiet nach einem nuklearen Unfall. Ein einzigartiges First-Person-Survival-Abenteuer voller britischer Dystopie, seltsamer Charaktere und dunkler Geheimnisse.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/801800/header.jpg',
     '2025-03-27'),
    ('The First Berserker: Khazan',
     'Ein anspruchsvolles Souls-like in der Welt von Dungeon Fighter Online. Du bist Khazan, ein gefallener General der nach Gerechtigkeit sucht. Brutale, technische Kämpfe und tiefgründige Dark-Fantasy-Lore.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/2680010/header.jpg',
     '2025-03-27'),
    ('South of Midnight',
     'Ein Action-Adventure im magischen amerikanischen Tiefen Süden. Hazel entdeckt ihre übernatürlichen Kräfte als Weaver und bekämpft Geister und Bestien aus echter Southern-Gothic-Folklore in einer wunderschönen Welt.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/1934570/header.jpg',
     '2025-04-08'),
    ('Mandragora: Whispers of the Witch Tree',
     'Ein düsteres Side-Scrolling-Action-RPG mit reicher Gothic-Atmosphäre. Erforsche eine verdorbene Welt als gefallener Dämonenjäger, sammle Artefakte und kämpfe gegen groteske Kreaturen der Finsternis.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/1721060/header.jpg',
     '2025-04-17'),
    ('Clair Obscur: Expedition 33',
     'Ein französisches Rundenkampf-RPG mit atemberaubendem Art-Design. Die Expedition 33 kämpft gegen den Maler Verso, der durch das Malen von Zahlen ganze Generationen auslöscht. Brillantes Narrativ und Kampfsystem.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/1903340/header.jpg',
     '2025-04-24'),
    ('DOOM: The Dark Ages',
     'Der Doom Slayer kämpft in einer mittelalterlichen Fantasy-Welt. Wielding Schild, Kettensäge und Pistolen gegen Dämonen und Drachen – die Vorgeschichte des ikonischen Slayers in seiner brutalsten Form.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/3017860/header.jpg',
     '2025-05-15'),
    ('ELDEN RING NIGHTREIGN',
     'Ein kooperativer Roguelite-Spinoff von Elden Ring für 1–3 Spieler. Erkunde eine dynamische Open World in rasanten Nightreign-Runs und besiege mächtige Nachtherren in immer wechselnden Herausforderungen.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/2622380/header.jpg',
     '2025-05-30'),
    ('REMATCH',
     'Ein rasantes kompetitives Multiplayer-Fussballspiel mit akrobatischen Manövern und intensiven 5v5-Matches. Keine klassischen Regeln – pure Skill, Teamplay und spektakuläre Aktionen dominieren das Spielfeld.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/2138720/header.jpg',
     '2025-06-05'),
    ('Stellar Blade',
     'EVE, eine atemberaubende Kriegerin aus dem Weltraum, kämpft um die Befreiung der Erde von alienbewohnten Aggressoren. Präzise Schwertkämpfe, cineastische Inszenierung und eine fesselnde Post-Apokalypse-Welt.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/3489700/header.jpg',
     '2025-06-11'),
    ('Dune: Awakening',
     'Ein Open-World-Survival-MMO im Universum von Dune. Erkunde die endlose Wüstenlandschaft Arrakis, hüte das kostbare Spice, überlebe Sandwürmer und kämpfe um politische Macht auf dem gefährlichsten Planeten der Galaxis.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/1172710/header.jpg',
     '2025-06-12'),
    ('The Alters',
     'Du bist auf einem fremden Planeten gestrandet und klonst alternative Versionen deiner selbst aus anderen Lebenspfaden. Jedes Alter hat andere Fähigkeiten und Persönlichkeit. Ein tiefgründiges Sci-Fi-Survival-Spiel.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/1601570/header.jpg',
     '2025-06-13'),
    ('FBC: Firebreak',
     'Ein kooperativer Ego-Shooter im Universum von Control. Bis zu drei Spieler bekämpfen paranormale Krisen im Federal Bureau of Control mit einzigartigen Waffen-Synergien und dynamischen Missionszielen.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/2272540/header.jpg',
     '2025-06-17'),
    ('MindsEye',
     'Ein dystopisches Action-Thriller-Spiel in einer von Tech-Konzernen kontrollierten Gesellschaft. Hack, kämpf und infiltriere als Protagonist mit einem KI-gestützten Hirn-Implant durch eine gefährliche Cyberpunk-Metropole.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/3265250/header.jpg',
     '2025-06-20'),
    ('WUCHANG: Fallen Feathers',
     'Ein atmosphärisches Souls-like im mythologischen China der Ming-Dynastie, befallen von übernatürlicher Korruption. Meistere tiefe Kampfmechaniken und erkunde prächtige, von Dunkelheit durchdrungene Umgebungen.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/2277560/header.jpg',
     '2025-07-01'),
    ('Mecha BREAK',
     'Ein kompetitiver Multiplayer-Mech-Shooter mit beeindruckend unterschiedlichen Mech-Klassen. Kämpfe in explosiven Luft-und-Boden-Schlachten, meistere einzigartige Spezialfähigkeiten und arbeite mit deinem Team zusammen.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/2452280/header.jpg',
     '2025-07-08'),
    ('Mafia: The Old Country',
     'Die Ursprünge der Mafia im Sizilien des frühen 20. Jahrhunderts. Erlebe den Aufstieg eines jungen Mannes in der Unterwelt in einem cinematischen Story-Driven-Gangster-Epos voller Ehre, Verrat und Gewalt.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/1941540/header.jpg',
     '2025-08-07'),
    ('Borderlands 4',
     'Die Vault Hunters kehren zurück auf einen neuen Planeten voller verrückter Bewohner und Milliarden von prozedural generierten Waffen. Neues Setting, neue Charaktere und der gewohnte Looter-Shooter-Wahnsinn mit Co-op-Action.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/1285190/header.jpg',
     '2025-09-12'),
    ('Lost Soul Aside',
     'Ein lang erwartetes Action-RPG aus China mit spektakulären Echtzeitkämpfen. Steuere einen jungen Krieger und sein Drachengefährt durch eine epische Fantasy-Welt in rasanten, choreografierten Kombokämpfen.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/3378960/header.jpg',
     '2025-09-25'),
    ('The Outer Worlds 2',
     'Obsidians satirisches Sci-Fi-RPG kehrt zurück in eine neue Galaxis voller korrupter Konzerne und skurriler Charaktere. Komplexe Fraktionen, epische Entscheidungsfreiheit und der gewohnte trockene Humor.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/1449110/header.jpg',
     '2025-10-29'),
    ('Crimson Desert',
     'Ein episches Action-RPG von Pearl Abyss. Spiele als Söldner Macduff und erkunde eine riesige Fantasy-Welt in atemberaubenden Schlachten gegen Monster, Armeen und legendäre Bosse mit filmreifer Inszenierung.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/3321460/header.jpg',
     '2025-12-05'),
    ('Fable',
     'Die legendäre Fable-Reihe kehrt zurück. Playground Games erschafft ein modernes Albion mit Open-World-Design, trockenem britischen Humor und den ikonischen moralischen Entscheidungen, die du und dein Charakter bereuen werden.',
     'https://cdn.cloudflare.steamstatic.com/steam/apps/2769570/header.jpg',
     '2026-05-07');

